#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# write_json_env KEY VALUE JSON_FILE — upsert a string value into a JSON
# dart-define file (env/dev.json is JSON, not KEY=VALUE, so the normal
# write_env can't touch it). Requires jq; otherwise records a manual TODO.
write_json_env() {
  local key="$1" value="$2" json_file="$3" tmp
  if ! command -v jq >/dev/null 2>&1; then
    SKIPPED+=("$json_file: set \"$key\": \"$value\" by hand (jq not installed)")
    warn "jq not found — add \"$key\": \"$value\" to $json_file yourself"
    return
  fi
  tmp=$(mktemp)
  jq --arg k "$key" --arg v "$value" '.[$k] = $v' "$json_file" > "$tmp"
  mv "$tmp" "$json_file"
  WRITTEN_ENV+=("$key -> $json_file")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$json_file"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_JSON="$PROJECT_ROOT/env/dev.json"
ANDROID_PACKAGE="com.myworkcmr.app"
IOS_BUNDLE_ID="com.myworkcmr.app"

banner "Fix Google Sign-In credentials (Google Cloud Console)"
say "Your app is hitting GoogleSignInException [28444] \"Developer console is"
say "not set up correctly\". That almost always means one of the three OAuth"
say "clients (Android / iOS / Web) is missing, mismatched, or the consent"
say "screen has no test users. We'll recheck/recreate all three."
note "Android package / iOS bundle ID: $ANDROID_PACKAGE"

# ── Stage 1: pick the project ─────────────────────────────────────────────
stage "Pick the Google Cloud project"
say "Your current client IDs live under project number 976085372569."
step "Decide: fix the existing project, or start clean with a new one."
step "If new: go to https://console.cloud.google.com/projectcreate, create it,"
step "then come back and open the credentials page for it."
open_url "https://console.cloud.google.com/apis/credentials"
step "Confirm (top-left project switcher) you're on the right project before continuing."
pause "In the right project? Press Enter to continue."

# ── Stage 2: SHA-1 fingerprint ────────────────────────────────────────────
stage "Get your SHA-1 signing fingerprint"
say "The Android OAuth client is matched by package name + SHA-1, not by an"
say "ID in code — a missing/wrong SHA-1 here is a classic cause of [28444]."
step "Run ONE of these from the project root, in another terminal:"
note "    cd android && ./gradlew signingReport"
note "    keytool -list -v -keystore ~/.android/debug.keystore \\"
note "        -alias androiddebugkey -storepass android -keypass android"
step "Copy the SHA1 line (looks like AA:BB:CC:...) for the variant you use to run/test"
step "(debug for local dev; repeat later for your release keystore before shipping)."
ask SHA1_FINGERPRINT "Paste the SHA-1 fingerprint:"

# ── Stage 3: OAuth consent screen ─────────────────────────────────────────
stage "OAuth consent screen — audience & test users"
say "If the app is in \"Testing\" publishing status, only test users you list"
say "can sign in — anyone else gets [28444] right after account selection."
open_url "https://console.cloud.google.com/auth/audience"
step "Check Publishing status: Testing or In production."
step "If Testing, add the Google account(s) you're testing with under Test users."
step "If this app is meant for anyone to sign in, consider moving to In production."
pause "Consent screen checked? Press Enter to continue."

# ── Stage 4: Android OAuth client ─────────────────────────────────────────
stage "Android OAuth client"
say "Package name: $ANDROID_PACKAGE"
say "SHA-1: $SHA1_FINGERPRINT"
open_url "https://console.cloud.google.com/apis/credentials"
step "Find an existing 'Android' client for this package — if its SHA-1 doesn't"
step "match what you pasted above, that's your bug: edit it (or delete + recreate)."
step "If none exists: + Create credentials → OAuth client ID → Android →"
step "  Package name: $ANDROID_PACKAGE"
step "  SHA-1 certificate fingerprint: $SHA1_FINGERPRINT"
note "This client has no client ID you paste into code — Google matches it"
note "automatically by package name + SHA-1 at sign-in time."
pause "Android client created/fixed? Press Enter to continue."

# ── Stage 5: iOS OAuth client ──────────────────────────────────────────────
stage "iOS OAuth client"
say "Bundle ID: $IOS_BUNDLE_ID"
open_url "https://console.cloud.google.com/apis/credentials"
step "+ Create credentials → OAuth client ID → iOS →"
step "  Bundle ID: $IOS_BUNDLE_ID"
step "(Or edit the existing iOS client if the bundle ID was wrong.)"
step "Copy the new Client ID (ends in .apps.googleusercontent.com)."
ask GOOGLE_IOS_CLIENT_ID "Paste the new iOS Client ID:"

# ── Stage 6: Web application OAuth client ─────────────────────────────────
stage "Web application OAuth client (used as the server/audience client ID)"
say "This is the one Supabase validates the Google ID token's audience against,"
say "and it's what your code passes as serverClientId."
open_url "https://console.cloud.google.com/apis/credentials"
step "+ Create credentials → OAuth client ID → Web application →"
step "  Name: e.g. 'mywork - Supabase Google auth'"
step "  Authorized redirect URIs: your Supabase project's callback URL, e.g."
note "    https://trlibcwsufpruksdyvlp.supabase.co/auth/v1/callback"
step "Copy the Client ID and Client secret (you'll need both next)."
ask GOOGLE_SERVER_CLIENT_ID "Paste the new Web Client ID:"
ask_secret GOOGLE_WEB_CLIENT_SECRET "Paste the new Web Client secret:"

# ── Stage 7: wire the new values into the app + Supabase ─────────────────
stage "Update env/dev.json and Supabase's Google provider"
write_json_env "GOOGLE_IOS_CLIENT_ID" "$GOOGLE_IOS_CLIENT_ID" "$DEV_JSON"
write_json_env "GOOGLE_SERVER_CLIENT_ID" "$GOOGLE_SERVER_CLIENT_ID" "$DEV_JSON"
if [[ -f "$PROJECT_ROOT/env/prod.json" ]]; then
  write_json_env "GOOGLE_IOS_CLIENT_ID" "$GOOGLE_IOS_CLIENT_ID" "$PROJECT_ROOT/env/prod.json"
  write_json_env "GOOGLE_SERVER_CLIENT_ID" "$GOOGLE_SERVER_CLIENT_ID" "$PROJECT_ROOT/env/prod.json"
fi
say "Now point Supabase at the same Web client so token validation matches:"
open_url "https://supabase.com/dashboard/project/trlibcwsufpruksdyvlp/auth/providers"
step "Open the Google provider, enable it, and paste in:"
step "  Client ID: $GOOGLE_SERVER_CLIENT_ID"
step "  Client secret: (the one you just copied)"
step "Save."
pause "Supabase Google provider updated? Press Enter to continue."

# ── Stage 8: rebuild and retest ───────────────────────────────────────────
stage "Rebuild and retest"
warn "Google Sign-In caches old config on-device — a hot reload won't pick this up."
step "Fully uninstall the app from your device/emulator (not just stop it)."
step "Rebuild and reinstall, e.g.:"
note "    flutter run --dart-define-from-file=env/dev.json"
step "Try Google Sign-In again with a test-user account from Stage 3."
pause "Press Enter once you've retested."

finish
note "Reminder: repeat the SHA-1 + Android client step for your RELEASE keystore"
note "before you ship a signed build — the debug SHA-1 alone won't work in prod."
